import ToolBar from "@/components/toolbar/toolbar";
import Footer from "@/components/footer/footer";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Amafel",
  description: "Generated by create next app",

  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "favicons/Light_apple-icon-180x180.png",
        href: "favicons/Light_apple-icon-180x180.png",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "favicons/Dark_apple-icon-180x180.png",
        href: "favicons/Dark_apple-icon-180x180.png",
      },
    ],
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <ToolBar />
          {children}
        </main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
